# Generated by Django 4.2.6 on 2023-11-01 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_playlist_recipes_recipestep'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='RecipeStep',
        ),
    ]
